name: bitcoin_bip44
version: 0.1.2
description: Library implementing Bitcoins BIP44 (HD wallet organization) specification in a Flutter friendly fashion.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  flutter:
    sdk: flutter

  base58check: ^1.0.1
  
  bitcoin_bip32: ^0.1.1

  bech32: ^0.1.2
    
  http: ^0.12.2

  pointycastle: ^1.0.2

dev_dependencies:
    test: ^1.14.2
    hex: ^0.1.2
    mock_web_server:
        git: https://github.com/haarts/MockWebServer.git
    pedantic: ^1.9.0

environment:
  sdk: ">=2.7.0 <3.0.0"
